### ISSUE TITLE
npm install le-challenge-dns installs le-challenge-ddns?

### ISSUE THREAD

**Issue by thadeetrompetter** [Daplie/le-challenge-dns#1]
When i run `npm install le-challenge-dns`, what actually gets installed appears to be [le-challenge-ddns](https://github.com/Daplie/le-challenge-ddns). According to its package page at npm, the correct repo  being pointed to from *le-challenge-dns* should indeed be *github.com/Daplie/le-challenge-dns*

**Comment by coolaj86** [comment]
I may have pushed the wrong version before. I just republished, try again now.

**Comment by thadeetrompetter** [comment]
looks good now, thanks!
